### ISSUE TITLE
rel8-0-0 somewhere in the code

### ISSUE THREAD

**Issue by Tomasito64** [JosephBARBIERDARNAL/autoSHARE#5]
![image](https://github.com/JosephBARBIERDARNAL/autoSHARE/assets/39495000/1964309f-769d-4f04-84b6-a436e91f701e)

There seems to be a rel8-0-0 somewhere in the code, or more specifically attached to a clone name.

**Comment by JosephBARBIERDARNAL** [comment]
this should now be fixed!

**Comment by Tomasito64** [comment]
Yep ! It seems ok now !

**Comment by Tomasito64** [comment]
Yep ! It seems ok now !

**Comment by Tomasito64** [comment]
It's ok !
