### ISSUE TITLE
Bug when adding duplicates in column list

### ISSUE THREAD

**Issue by Tomasito64** [JosephBARBIERDARNAL/autoSHARE#6]
![image](https://github.com/JosephBARBIERDARNAL/autoSHARE/assets/39495000/d3f2b391-9a56-4b1e-a002-9a4470ccd834)

When you choose a column name that's already in your list, there's a bug. 
We need to disallow this action, probably with an "if" function.

In the instance above: Language and Language

**Comment by Tomasito64** [comment]
Hmm, two possibilities: either you've corrected it, or (for a 5-minute question) I didn't have the right version because now, when I choose a variable, it disappears.
So this is no longer a problem.

**Comment by JosephBARBIERDARNAL** [comment]
this bug is now fixed! we can close the issue now
