### ISSUE TITLE
Incompatibility ? 

### ISSUE THREAD

**Issue by Tomasito64** [JosephBARBIERDARNAL/autoSHARE#8]
![image](https://github.com/JosephBARBIERDARNAL/autoSHARE/assets/39495000/13e0c3bf-a953-4b17-a621-ea7db5baba21)

The "weight" variable seems to cause a problem. But if I remove mergeid2, everything's fine. There seem to be incompatibility problems between some variables. When you put variables together, it's a crach !

**Comment by JosephBARBIERDARNAL** [comment]
this is suposively fixed now!
