### ISSUE TITLE
Welcome suspect !

### ISSUE THREAD

**Issue by Tomasito64** [JosephBARBIERDARNAL/autoSHARE#9]
![image](https://github.com/JosephBARBIERDARNAL/autoSHARE/assets/39495000/56336119-7981-4a87-ae36-40639de53a83)

I find it very suspicious that the ID (mergeid) appears 5 times in the final dataset.

**Comment by JosephBARBIERDARNAL** [comment]
can you show the full `mergeid` by enlarging the columns?

**Comment by Tomasito64** [comment]
![image](https://github.com/JosephBARBIERDARNAL/autoSHARE/assets/39495000/d73d038c-5a64-41f0-be10-7a0732824ffb)

It's the same bro!!!

**Comment by JosephBARBIERDARNAL** [comment]
this should be fixed now! I close the issue
